/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 computer.gltf 
Author: dark_igorek (https://sketchfab.com/dark_igorek)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/apple-ii-computer-b5d316548d634f16a72dd503db0aa01b
Title: Apple II Computer
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export default function Model(props) {
  // const { nodes, materials } = useGLTF('/Michael/computer.gltf')
  const { nodes, materials } = useGLTF('./computer.gltf')
  return (
    <group {...props} dispose={null}>
      <group position={[-0.059, 0.095, -0.025]} scale={0.138}>
        <mesh geometry={nodes.Object_4.geometry} material={materials.appleII_body_mat} />
        <mesh geometry={nodes.Object_6.geometry} material={materials.appleII_details_mat} position={[0.035, -0.533, 0.819]} />
        <mesh geometry={nodes.Object_8.geometry} material={materials.plugs_mat} position={[0.068, -0.133, 0.143]} />
        <mesh geometry={nodes.Object_10.geometry} material={materials.appleII_body_mat} position={[0.018, 0.087, -0.007]} />
        <mesh geometry={nodes.Object_12.geometry} material={materials.appleII_details_mat} position={[0.797, -0.526, -1.063]} />
        <mesh geometry={nodes.Object_14.geometry} material={materials.appleII_keyboard_mat} position={[-0.395, -0.178, 1.879]} />
        <mesh geometry={nodes.Object_16.geometry} material={materials.appleII_details_mat} position={[-0.95, -0.505, -1.188]} />
      </group>
      <group position={[0.247, 0.055, -0.068]} scale={0.138}>
        <mesh geometry={nodes.Object_24.geometry} material={materials.diskII_mat} />
        <mesh geometry={nodes.Object_26.geometry} material={materials.plugs_mat} />
        <mesh geometry={nodes.Object_28.geometry} material={materials.diskII_mat} position={[-0.45, 0.222, 0.832]} />
      </group>
      <group position={[0.247, 0.157, -0.068]} scale={0.138}>
        <mesh geometry={nodes.Object_30.geometry} material={materials.diskII_mat} />
        <mesh geometry={nodes.Object_32.geometry} material={materials.plugs_mat} />
        <mesh geometry={nodes.Object_34.geometry} material={materials.diskII_mat} position={[-0.45, 0.221, 0.832]} />
      </group>
      <group position={[-0.044, 0.203, -0.065]} scale={0.138}>
        <mesh geometry={nodes.Object_36.geometry} material={materials.monitor_base_mat} />
        <mesh geometry={nodes.Object_38.geometry} material={materials.Monitor_details_mat} position={[-0.313, 0.486, -0.725]} />
        <mesh geometry={nodes.Object_40.geometry} material={materials.plugs_mat} position={[-0.303, 0.278, -0.297]} />
        <mesh geometry={nodes.Object_42.geometry} material={materials.monitor_screen_mat} position={[-0.313, 0.495, 0.516]} />
      </group>
      <mesh geometry={nodes.Object_18.geometry} material={materials.cable_mat} position={[-0.062, -0.036, 0.022]} scale={0.138} />
      <mesh geometry={nodes.Object_20.geometry} material={materials.cable_mat} position={[-0.062, -0.036, 0.022]} scale={0.138} />
      <mesh geometry={nodes.Object_22.geometry} material={materials.cable_mat} position={[0.073, 0.024, -0.197]} rotation={[-Math.PI / 2, 0, 0]} scale={0.138} />
    </group>
  )
}

// useGLTF.preload('/Michael/computer.gltf')
useGLTF.preload('./computer.gltf')